guilds:
- name: NAPS
  roles:
    relevantParsing: true
    relevantFlexing: true
    relevantRepetition: true
    legend: true
    ultimateFlexing: true
    ultimateRepetition: true
    datacenter: true
  guildId: 1008845758805594173
  channelId: 1008850017185955850
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [91]
    name: "P12S"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P12S-Cleared"
        type: "Cleared"
        color: 0xef8633
  - ids: [90]
    name: "P11S"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P11S-Cleared"
        type: "Cleared"
        color: 0x9644e5
  - ids: [89]
    name: "P10S"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P10S-Cleared"
        type: "Cleared"
        color: 0x2a72f6
  - ids: [88]
    name: "P9S"
    difficulty: "Savage"
    defaultRoles: true
    roles:
      - name: "P9S-Cleared"
        type: "Cleared"
        color: 0x78fa4c
    clearedColor: 0x78fa4c
- name: APD
  roles:
    relevantParsing: true
    relevantFlexing: true
    relevantRepetition: true
    legend: true
    ultimateFlexing: true
    ultimateRepetition: true
    datacenter: true
  guildId: 968960259081252884
  channelId: 972868045552877589
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    roles:
      - name: "Cleared"
        type: "Cleared"
        color: 0xf58cba
    prog:
    - name: Vault Knights
      color: 0x9C491B
      hoist: false
    - name: Thordan
      color: 0x693986
      hoist: false
      mention: false
    - name: Nidstinien
      color: 0x356590
      hoist: false
      mention: false
    - name: The Eyes
      color: 0x596D79
      hoist: false
      mention: false
    - name: Thordan Reprise
      color: 0x925CB1
      hoist: false
      mention: false
    - name: Double Dragon
      color: 0x5195D3
      hoist: false
      mention: false
    - name: Dragon-king Thordan
      color: 0xE8C444
      hoist: false
      mention: false
  reconfigureRoles:
  - from: "Heavenly"
    skip: true
  - from: "Heavenly Limbo"
    skip: true
- name: UAR
  roles:
    relevantParsing: true
    relevantFlexing: false
    relevantRepetition: false
    legend: true
    ultimateFlexing: true
    ultimateRepetition: true
    datacenter: true
  guildId: 973884326515191838
  channelId: 1028344695597838356
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Legendary"
    roles:
      - name: "UCoB Cleared"
        type: "Cleared"
        color: 0xFFFD7F
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Ultimate"
    roles:
      - name: "UWU Cleared"
        type: "Cleared"
        color: 0x9CBDD8
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 17
    the: "Perfect"
    roles:
      - name: "TEA Cleared"
        type: "Cleared"
        color: 0xFAE9C2
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    the: "Heavenly"
    roles:
      - name: "DSR Cleared"
        type: "Cleared"
        color: 0xCF8035
  - ids: [1068]
    name: "The Omega Protocol (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    the: "Alpha"
    roles:
      - name: "TOP Cleared"
        type: "Cleared"
        color: 0xd1e5f4
- name: UDR
  roles:
    relevantParsing: true
    relevantFlexing: false
    relevantRepetition: false
    legend: true
    ultimateFlexing: true
    ultimateRepetition: false
    datacenter: true
  guildId: 1021602454716022845
  channelId: 1037083485543866479
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Legendary"
    roles:
      - name: "i killed ucob"
        type: "Cleared"
        color: 0xb89c00
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Ultimate"
    roles:
      - name: "i killed uwu"
        type: "Cleared"
        color: 0x23f3f7
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 17
    the: "Perfect"
    roles:
      - name: "i killed tea"
        type: "Cleared"
        color: 0xf5cbff
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    the: "Heavenly"
    roles:
      - name: "i killed dsr"
        type: "Cleared"
        color: 0xD8833B
  reconfigureRoles:
  - from: "The Quad Legend"
    to: "dodge on sight"
    color: 0xff0003
- name: UPR
  roles:
    relevantParsing: false
    relevantFlexing: false
    relevantRepetition: false
    legend: false
    ultimateFlexing: false
    ultimateRepetition: false
    datacenter: true
  guildId: 404710160540368917
  channelId: 1028389598755311657
  physicalDatacenters:
  - name: "NA"
    logicalDatacenters:
      - to: "aether guest"
        from: "Aether"
        color: 0x000001
      - to: "crystal guest"
        from: "Crystal"
        color: 0xf9c9a9
      - to: "primal guest"
        from: "Primal"
        color: 0xff0000
      - to: "dynamis guest"
        from: "Dynamis"
        color: 0xEAC645
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared Ucob"
        type: "Cleared"
        color: 0xEAC645
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared UwU"
        type: "Cleared"
        color: 0x3bbdf5
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared TEA"
        type: "Cleared"
        color: 0x65C97A
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    roles:
      - name: "Cleared DSR"
        type: "Cleared"
        color: 0xb660ff
- name: Ultimate Uncoiled
  roles:
    relevantParsing: false
    relevantFlexing: true
    relevantRepetition: false
    legend: true
    ultimateFlexing: false
    ultimateRepetition: false
    datacenter: false
    skipRemoval: true
  guildId: 556243090256560129
  channelId: 1052040182330822727
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared ucob"
        type: "Cleared"
        color: 0xf8ff00
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared uwu"
        type: "Cleared"
        color: 0x30d2fb
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared tea"
        type: "Cleared"
        color: 0x2daf55
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared dru"
        type: "Cleared"
        color: 0xe67cba
  - ids: [1068]
    name: "The Omega Protocol (Ultimate)"
    defaultRoles: false
    roles:
      - name: "cleared top"
        type: "Cleared"
        color: 0x3498db
  reconfigureRoles:
  - from: "NA's Comfiest"
    to: "comfiest"
  - from: "Nice"
    to: "nice"
  - from: "Chad"
    to: "chad"
  - from: "Bloodbather"
    to: "bloodbather"
  - from: "Overhealer"
    to: "overhealer"
  - from: "Rainbow"
    to: "rainbow"
  - from: "The Man"
    to: "the man"
    dontSkip: true
  - from: "The Myth"
    to: "the myth"
    dontSkip: true
  - from: "The Uncoiled Legend"
    to: "the legend (over time)"
    dontSkip: true
  - from: "The Legend"
    skip: true
  - from: "The Double Legend"
    skip: true
  - from: "The Triple Legend"
    to: "triplelegendbtw"
    color: 0xb57edc
  - from: "The Quad Legend"
    to: "tetrislegendbtw"
    color: 0xffa6c9
- name: TOP
  roles:
    relevantParsing: true
    relevantFlexing: true
    relevantRepetition: true
    legend: true
    ultimateFlexing: true
    ultimateRepetition: true
    datacenter: true
  guildId: 982459453578285056
  channelId: 1073363433489170442
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1068]
    name: "The Omega Protocol (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    roles:
      - name: "ALPHA LEGEND"
        type: "Cleared"
        color: 0xf58cba
        hoist: true
    prog:
    - name: Omega
      color: 0x693986
      hoist: true
    - name: Omega-M/F
      color: 0x356590
      hoist: true
    - name: Omega Reconfigured
      color: 0x596D79
      hoist: true
    - name: Blue Screen
      color: 0x925CB1
      hoist: true
    - name: "Run: Dynamis"
      color: 0x6fd9f3
      hoist: true
    - name: Alpha Omega
      color: 0xE8C444
      hoist: true
  reconfigureRoles:
  - from: "Alpha"
    skip: true
  - from: "Alpha Limbo"
    skip: true
- name: Savage Learning Academy
  roles:
    relevantParsing: false
    relevantFlexing: false
    relevantRepetition: false
    legend: true
    ultimateFlexing: false
    ultimateRepetition: false
    datacenter: true
  guildId: 633011544652906496
  channelId: 1117189354687828048
  physicalDatacenters:
  - name: "NA"
    logicalDatacenters:
      - to: "Aether"
        from: "Aether"
        color: 0x8667f5
      - to: "Crystal"
        from: "Crystal"
        color: 0x6bf5b5
      - to: "Primal"
        from: "Primal"
        color: 0x59d0e6
      - to: "Dynamis"
        from: "Dynamis"
        color: 0x99a7f7
  encounters:
  - ids: [92]
    name: "P12S P2"
    difficulty: "Savage"
    defaultRoles: false
    requiredKillsToClear: 3
    roles:
      - name: "Cleared p12s p2"
        type: "Cleared"
        color: 0xa200ff
  - ids: [91]
    name: "P12S P1"
    difficulty: "Savage"
    defaultRoles: false
    requiredKillsToClear: 3
    roles:
      - name: "Cleared p12s p1"
        type: "Cleared"
        color: 0xa8a8a8
  - ids: [90]
    name: "P11S"
    difficulty: "Savage"
    defaultRoles: false
    requiredKillsToClear: 3
    roles:
      - name: "Cleared p11s"
        type: "Cleared"
        color: 0x00ff03
  - ids: [89]
    name: "P10S"
    difficulty: "Savage"
    defaultRoles: false
    requiredKillsToClear: 3
    roles:
      - name: "Cleared p10s"
        type: "Cleared"
        color: 0xfffb00
  - ids: [88]
    name: "P9S"
    difficulty: "Savage"
    defaultRoles: false
    requiredKillsToClear: 3
    roles:
      - name: "Cleared p9s"
        type: "Cleared"
        color: 0xff0000
  reconfigureRoles:
  - from: "The Legend"
    to: "<Legend>"
    color: 0x947a27
  - from: "The Double Legend"
    to: "<Double Legend>"
    color: 0x947a27
  - from: "The Triple Legend"
    to: "<Triple Legend>"
    color: 0x947a27
  - from: "The Quad Legend"
    to: "<Quad Legend>"
    color: 0x947a27
  - from: "The Penta Legend"
    to: "<Penta Legend>"
    color: 0x947a27
- name: Golden Sheep (Ultimates)
  roles:
    relevantParsing: false
    relevantFlexing: false
    relevantRepetition: false
    legend: true
    ultimateFlexing: false
    ultimateRepetition: false
    datacenter: false
  guildId: 1150614296942878860
  channelId: 1168315554621296730
  physicalDatacenters:
  - name: "NA"
  encounters:
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Legendary"
    roles:
      - name: "The Sheep"
        type: "Cleared"
        color: 0xFFFD7F
        hoist: true
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Ultimate"
    roles:
      - name: "The Ultimate Sheep"
        type: "Cleared"
        color: 0x9CBDD8
        hoist: true
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 17
    the: "Perfect"
    roles:
      - name: "The Perfect Sheep"
        type: "Cleared"
        color: 0xFAE9C2
        hoist: true
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    the: "Heavenly"
    roles:
      - name: "The Heavens' Sheep"
        type: "Cleared"
        color: 0xCF8035
        hoist: true
  - ids: [1068]
    name: "The Omega Protocol (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    the: "Alpha"
    roles:
      - name: "The Alpha Sheep"
        type: "Cleared"
        color: 0xd1e5f4
        hoist: true
  reconfigureRoles:
  - from: "The Legend"
    color: 0x0ec0a5
  - from: "The Double Legend"
    color: 0x0ec0a5
  - from: "The Triple Legend"
    color: 0x0ec0a5
  - from: "The Quad Legend"
    color: 0x0ec0a5
  - from: "The Penta Legend"
    color: 0x0ec0a5
- name: NAUR
  roles:
    relevantParsing: true
    relevantFlexing: true
    relevantRepetition: true
    legend: true
    ultimateFlexing: false
    ultimateRepetition: false
    datacenter: true
  guildId: 1172230157776466050
  channelId: 1172348608671133760
  physicalDatacenters:
  - name: "NA"
    logicalDatacenters:
      - to: "Aether Resident"
        from: "Aether"
        color: 0x71368a
        hoist: true
      - to: "Crystal Resident"
        from: "Crystal"
        color: 0x206694
        hoist: true
      - to: "Primal Resident"
        from: "Primal"
        color: 0x992d22
        hoist: true
      - to: "Dynamis Resident"
        from: "Dynamis"
        color: 0xEAC645
        hoist: true
  encounters:
  # Changed initial cleared role colors
  - ids: [1060, 1047, 1039]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Legendary"
    roles:
      - name: "UCoB Cleared"
        type: "Cleared"
        color: 0xfdfd96
  - ids: [1061, 1048, 1042]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 15
    the: "Ultimate"
    roles:
      - name: "UWU Cleared"
        type: "Cleared"
        color: 0x97cae3
  - ids: [1062, 1050]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 17
    the: "Perfect"
    roles:
      - name: "TEA Cleared"
        type: "Cleared"
        color: 0xfae9c2
  - ids: [1065]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    the: "Heavenly"
    roles:
      - name: "DSR Cleared"
        type: "Cleared"
        color: 0xc9843f
  - ids: [1068]
    name: "The Omega Protocol (Ultimate)"
    defaultRoles: false
    totalWeaponsAvailable: 19
    the: "Alpha"
    roles:
      - name: "TOP Cleared"
        type: "Cleared"
        color: 0x6534c6
  reconfigureRoles:
  - from: "Please Do Other Content"
    hoist: true
  # Rename ultimate Limbo roles so they are more accurate
  - from: "Limbo"
    type: "Limbo"
    encounterName: "The Unending Coil of Bahamut (Ultimate)"
    to: "Legendary Limbo"
  - from: "Limbo"
    type: "Limbo"
    encounterName: "The Weapon's Refrain (Ultimate)"
    to: "Ultimate Limbo"
  - from: "Limbo"
    type: "Limbo"
    encounterName: "The Epic of Alexander (Ultimate)"
    to: "Perfect Limbo"
  - from: "Limbo"
    type: "Limbo"
    encounterName: "Dragonsong's Reprise (Ultimate)"
    to: "Heavenly Limbo"
  - from: "Limbo"
    type: "Limbo"
    encounterName: "The Omega Protocol (Ultimate)"
    to: "Alpha Limbo"
  # Rename ultimate Complete roles so they are more accurate
  - from: "Complete"
    type: "Complete"
    encounterName: "The Unending Coil of Bahamut (Ultimate)"
    to: "Legendary"
  - from: "Complete"
    type: "Complete"
    encounterName: "The Weapon's Refrain (Ultimate)"
    to: "Ultimate"
  - from: "Complete"
    type: "Complete"
    encounterName: "The Epic of Alexander (Ultimate)"
    to: "Perfect"
  - from: "Complete"
    type: "Complete"
    encounterName: "Dragonsong's Reprise (Ultimate)"
    to: "Heavenly"
  - from: "Complete"
    type: "Complete"
    encounterName: "The Omega Protocol (Ultimate)"
    to: "Alpha"
- name: Deep Dungeon
  roles:
    relevantParsing: false
    relevantFlexing: false
    relevantRepetition: false
    legend: false
    ultimateFlexing: false
    ultimateRepetition: false
    datacenter: true
  guildId: 1021602454716022845
  channelId: 1172348608671133760
  achievements:
    - name: "Pal-less Palace III"
      roles:
        - name: "Pal-less Palace"
          description: "Pal-less Palace III"
          type: "Palace of the Dead"
          color: 0x8b0000
    - name: "The Necromancer"
      roles:
        - name: "The Necromancer"
          description: "The Necromancer"
          type: "Palace of the Dead"
          color: 0x8b0000
    - name: "Heaven Is a Lonely Place II"
      roles:
        - name: "Heaven Is a Lonely Place"
          description: "Heaven Is a Lonely Place II"
          type: "Heaven on High"
          color: 0xFFD580
    - name: "Lone Hero"
      roles:
        - name: "Lone Hero"
          description: "Lone Hero"
          type: "Heaven on High"
          color: 0xFFD580
    - name: "All by Eurekaself II"
      roles:
        - name: "All by Eurekaself"
          description: "All by Eurekaself II"
          type: "Eureka"
          color: 0x739BD0
    - name: "Once and Future King / Queen"
      roles:
        - name: "Once and Future King / Queen"
          description: "Once and Future King / Queen"
          type: "Cleared"
          color: 0x739BD0
